-- Part 1: Set up the hero_slides table
CREATE TABLE IF NOT EXISTS hero_slides (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    subtitle TEXT,
    image_url TEXT NOT NULL,
    link_url TEXT NOT NULL DEFAULT '#',
    button_text TEXT NOT NULL DEFAULT 'Shop Now',
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on hero_slides table
ALTER TABLE hero_slides ENABLE ROW LEVEL SECURITY;

-- Drop existing policies for hero_slides table
DROP POLICY IF EXISTS "Public can view hero slides" ON hero_slides;
DROP POLICY IF EXISTS "Authenticated users can manage hero slides" ON hero_slides;

-- Create policies for hero_slides table
CREATE POLICY "Public can view hero slides"
ON hero_slides FOR SELECT
USING (true);

CREATE POLICY "Authenticated users can manage hero slides"
ON hero_slides FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- Part 2: Set up the storage bucket and policies
-- Ensure the bucket exists and is public
INSERT INTO storage.buckets (id, name, public)
VALUES ('hero-slides', 'hero-slides', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Enable RLS on storage.objects
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- Drop existing policies for storage
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can update files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete files" ON storage.objects;

-- Create storage policies
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING (bucket_id = 'hero-slides');

CREATE POLICY "Authenticated users can upload files"
ON storage.objects FOR INSERT
WITH CHECK (
    bucket_id = 'hero-slides' 
    AND auth.role() = 'authenticated'
);

CREATE POLICY "Authenticated users can update files"
ON storage.objects FOR UPDATE
USING (
    bucket_id = 'hero-slides' 
    AND auth.role() = 'authenticated'
);

CREATE POLICY "Authenticated users can delete files"
ON storage.objects FOR DELETE
USING (
    bucket_id = 'hero-slides' 
    AND auth.role() = 'authenticated'
);

-- Grant necessary permissions
GRANT ALL ON hero_slides TO authenticated;
GRANT SELECT ON hero_slides TO anon;
GRANT ALL ON storage.objects TO authenticated;
GRANT SELECT ON storage.objects TO anon;
GRANT USAGE ON SCHEMA storage TO anon, authenticated;

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_hero_slides_updated_at
    BEFORE UPDATE ON hero_slides
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
